server:
  port: 8101
spring:
  application:
    name: edu-microservice
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/edu?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 时间格式化
    time-zone: GMT+8 # 时区设置为东八区


# 日志配置


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com.liao: debug
  file:
    path: /log/edu

# 配置注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
