server:
  port: 8251

spring:
  application:
    name: edu-minio-video-web
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
feign:
  hystrix:
    enabled: false
  client:
    config:
      edu-minio-video:
        connectTimeout: 500000
        readTimeout: 500000




