server:
  port: 8151

spring:
  application:
    name: edu-microservice-web
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
feign:
  hystrix:
    enabled: true


